### ISSUE TITLE
Could you upload one release or add build guide?

### ISSUE THREAD

**Issue by kiddlu** [vhanla/DarkDesktop#3]
Ths!

**Comment by vhanla** [comment]
Just use Delphi with components (Graphics32) and compile.

Here is an old release:
[DarkDesktopEN.zip](https://github.com/vhanla/DarkDesktop/files/6298130/DarkDesktopEN.zip)
And current WIP (incomplete):
[DarkDesktopWIP.zip](https://github.com/vhanla/DarkDesktop/files/6298139/DarkDesktopWIP.zip)

**Comment by kiddlu** [comment]
Thank you very much！
